version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGH1809Project
  gitServerName: src_shared_GithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
